// Lunr.js search integration for Jekyll
// Assumes /search.json is generated by jekyll-lunr-js-search

document.addEventListener('DOMContentLoaded', function() {
  var lunrIndex = null;
  var lunrData = [];
  var searchBox = document.getElementById('lunr-search-box');
  var resultsDiv = document.getElementById('lunr-search-results');

  // Fetch the search index
  fetch('/search.json')
    .then(function(response) { return response.json(); })
    .then(function(data) {
      lunrData = data;
      lunrIndex = lunr(function() {
        this.ref('id');
        this.field('title', { boost: 10 });
        this.field('content');
        this.field('url');
        var that = this;
        lunrData.forEach(function(doc, idx) {
          doc.id = idx;
          that.add(doc);
        });
      });
    });

  // Search handler
  searchBox.addEventListener('input', function() {
    var query = searchBox.value.trim();
    if (!lunrIndex || !query) {
      resultsDiv.innerHTML = '';
      return;
    }
    var results = lunrIndex.search(query);
    if (results.length === 0) {
      resultsDiv.innerHTML = '<p>No results found.</p>';
      return;
    }
    var html = '<ul>';
    results.forEach(function(result) {
      var doc = lunrData[result.ref];
      html += '<li><a href="' + doc.url + '">' + doc.title + '</a></li>';
    });
    html += '</ul>';
    resultsDiv.innerHTML = html;
  });
}); 